### ISSUE TITLE
Todo-isms

### ISSUE THREAD

**Issue by NotUnlikeTheWaves** [NotUnlikeTheWaves/ini-editor#1]
Collection topic for many things still to do:

- [ ] API documentation (find something for this)
- [ ] In /api/v1/filelist, return:
- Path
- Size
- Date created+modified
- All metadata from the [web-metadata] tag

- [ ] In `/api/v1/file/:path`, a JSON view of the file in the form of:
```json
[{ 
  "section" : {
    "description": "Comment describing this section",
    "keys": {
      "key": "keyname",
      "value": 1234,
      "description": "Comment describing this key"
    }
  }
}]
```
Corresponding to the file format:
```ini
[section]
; Comment describing this section
keyname=1234
; Comment describing this key

```
